name: Build_FF_H5GG
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Theos
        uses: theos/setup-theos@master # Sửa lỗi "not found" triệt để
      - name: Build
        run: |
          unzip -o src.zip
          make package FINALPACKAGE=1
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Mod_H5GG_Cua_Ban
          path: packages/*.tipa
